eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/StevenZhaoJ/SpringCloud
          search-paths: test
          username: StevenZhaoJ
          password: zhaojie521
  application:
    name: config-server
