server:
  port: 8010
spring:
  application:
    name: movie-consumer-user
eureka:
  client:
    service-url:
#      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
      defaultZone: http://user:user@peer1:8761/eureka/
  instance:
    # register own IP in eureka
    prefer-ip-address: true
