server:
  port: 8010
spring:
  application:
    name: movie-consumer-user
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  instance:
    # 将自己的IP注册到Eureka中
    prefer-ip-address: true
